### ISSUE TITLE
Tuple coder test isn't mutually corresponding and not well ordered.

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/wakkanay-tezos#15]
test encode tuple
https://github.com/cryptoeconomicslab/wakkanay-tezos/blob/master/__tests__/coder/TzCoder.test.ts#L39

test decode list of tuple
https://github.com/cryptoeconomicslab/wakkanay-tezos/blob/master/__tests__/coder/TzCoder.test.ts#L176

**Comment by syuhei176** [comment]
test decode tuple is [here](https://github.com/cryptoeconomicslab/wakkanay-tezos/blob/master/__tests__/coder/TzCoder.test.ts#L150).

However, there might be another non-corresponding, order of attributes is different between encode and decode in Tuple and Struct.

**Comment by shogochiai** [comment]
@daiki44 How do you think is this reasonable to make a patch? And if any I will do that.

- [ ] Add an "encode List of Tuple" testcase.
- [ ] Order testcases as maintainers easily can confirm those testcases are collectively matching with contract-side test.

**Comment by daiki44** [comment]
@shogochiai 
Sorry, I can't decide that now. Could you tell me the issue's background more?
But you can update the code if needed basically.
Because I guess the coder has some update points depending on the contract.


> The order of attributes is different between encode and decode in Tuple and Struct.

By the way, I want to know about it more.
What support should I do in Coder?
